name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - name: Run DB Migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          npx supabase link --project-ref $SUPABASE_PROJECT_REF --password $DB_PASSWORD
          npx supabase db push --password $DB_PASSWORD
